// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddPWASupport
{
    static class Vsix
    {
        public const string Id = "c140d5d7-6be7-41da-a3b4-785f479b825e";
        public const string Name = "PWA Support";
        public const string Description = @"This project helps you to add Progressive Web App support to your web app";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Congiu Luca";
        public const string Tags = "PWA, Progressive Web App";
    }
}
